begin;

create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;

select plan(8);

select ok(
  has_table_privilege('service_role', 'public.user_legal_acceptances', 'SELECT'),
  'trusted backend maintenance can inspect legal acceptance evidence'
);
select ok(
  not has_table_privilege('anon', 'public.user_legal_acceptances', 'SELECT')
  and not has_table_privilege('authenticated', 'public.user_legal_acceptances', 'SELECT')
  and not has_table_privilege('authenticated', 'public.user_legal_acceptances', 'INSERT')
  and not has_table_privilege('authenticated', 'public.user_legal_acceptances', 'UPDATE')
  and not has_table_privilege('authenticated', 'public.user_legal_acceptances', 'DELETE'),
  'browser roles cannot read or alter legal acceptance evidence directly'
);
select ok(
  not has_function_privilege('anon', 'public.capture_signup_legal_acceptance()', 'EXECUTE')
  and not has_function_privilege('authenticated', 'public.capture_signup_legal_acceptance()', 'EXECUTE'),
  'browser roles cannot call the signup evidence trigger function'
);

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at
) values
  (
    '00000000-0000-0000-0000-000000000000',
    'a1000000-0000-4000-8000-000000000001',
    'authenticated', 'authenticated', 'legal-accepted@example.test',
    crypt('LocalTestOnly!2026', gen_salt('bf')), null, '', '', '', '',
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Accepted Candidate","legal_acceptance":true,"legal_acceptance_source":"email_signup"}',
    now(), now()
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    'a1000000-0000-4000-8000-000000000002',
    'authenticated', 'authenticated', 'legal-missing@example.test',
    crypt('LocalTestOnly!2026', gen_salt('bf')), null, '', '', '', '',
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Unaccepted Candidate"}',
    now(), now()
  );

select is(
  (select count(*)::integer from public.user_legal_acceptances where user_id = 'a1000000-0000-4000-8000-000000000001'),
  1,
  'affirmative signup metadata creates one server-side acceptance record'
);
select is(
  (select terms_version from public.user_legal_acceptances where user_id = 'a1000000-0000-4000-8000-000000000001'),
  '2026-07-19',
  'the server records the current Terms version'
);
select is(
  (select privacy_version from public.user_legal_acceptances where user_id = 'a1000000-0000-4000-8000-000000000001'),
  '2026-07-19',
  'the server records the current Privacy Policy version'
);
select ok(
  (select accepted_at <= clock_timestamp() and accepted_at > clock_timestamp() - interval '1 minute'
   from public.user_legal_acceptances where user_id = 'a1000000-0000-4000-8000-000000000001'),
  'the acceptance time is generated by the server'
);
select is(
  (select count(*)::integer from public.user_legal_acceptances where user_id = 'a1000000-0000-4000-8000-000000000002'),
  0,
  'missing acceptance metadata never creates affirmative evidence'
);

select * from finish();
rollback;
