export const SERVICE_LEVELS = [
  "GL 07",
  "GL 08",
  "GL 09",
  "GL 10",
  "GL 11",
  "GL 12",
  "GL 13",
  "GL 14",
  "GL 15",
  "GL 16",
  "GL 17",
  "Permanent Secretary",
];

export const EXAM_MODULES = [
  {
    id: null,
    slug: "public-financial-management",
    name: "Public Financial Management",
    description: "Financial Regulations, accountability, approvals, and expenditure control.",
    sort_order: 1,
  },
  {
    id: null,
    slug: "public-service-rules",
    name: "Public Service Rules",
    description: "Conduct, discipline, appointments, and service-wide administrative rules.",
    sort_order: 2,
  },
  {
    id: null,
    slug: "current-affairs",
    name: "Current Affairs",
    description: "Governance, history, national issues, and general knowledge.",
    sort_order: 3,
  },
];

export const NIGERIA_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];
