create table public.user_legal_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  source text not null,
  accepted_at timestamptz not null default clock_timestamp(),
  constraint user_legal_acceptances_terms_version_present check (btrim(terms_version) <> ''),
  constraint user_legal_acceptances_privacy_version_present check (btrim(privacy_version) <> ''),
  constraint user_legal_acceptances_source_valid check (source in ('email_signup', 'oauth_consent', 'renewal')),
  constraint user_legal_acceptances_version_once unique (user_id, terms_version, privacy_version)
);

comment on table public.user_legal_acceptances is
  'Append-only evidence that a user affirmatively accepted versioned legal documents.';
comment on column public.user_legal_acceptances.accepted_at is
  'Server-generated time when PromotionSure received the affirmative action.';

create index user_legal_acceptances_user_accepted_idx
  on public.user_legal_acceptances (user_id, accepted_at desc);

alter table public.user_legal_acceptances enable row level security;
revoke all on table public.user_legal_acceptances from public, anon, authenticated;
grant select on table public.user_legal_acceptances to service_role;

create or replace function public.capture_signup_legal_acceptance()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.raw_user_meta_data ->> 'legal_acceptance' = 'true'
     and new.raw_user_meta_data ->> 'legal_acceptance_source' = 'email_signup' then
    insert into public.user_legal_acceptances (
      user_id,
      terms_version,
      privacy_version,
      source
    ) values (
      new.id,
      '2026-07-19',
      '2026-07-19',
      'email_signup'
    )
    on conflict (user_id, terms_version, privacy_version) do nothing;
  end if;

  return new;
end;
$$;

revoke all on function public.capture_signup_legal_acceptance() from public, anon, authenticated;

drop trigger if exists on_auth_user_legal_acceptance on auth.users;
create trigger on_auth_user_legal_acceptance
after insert on auth.users
for each row execute function public.capture_signup_legal_acceptance();
